### ISSUE TITLE
WormClust web server availability

### ISSUE THREAD

**Issue by n-szulc** [WalhoutLab/WormClust#1]
Hello

how can I use the WormClust web server? I cannot find any link/manual at wormflux.umassmed.edu

Best regards

**Comment by shivani710** [comment]
Hi Natalia

The paper related to WormClust is under peer review. That is why it is not
available directly on WormFlux yet. However, you can access the WormClust
web server using public link:
http://wormflux.umassmed.edu/WormClust/wormclust.php

Please let us know if you have any questions or feedback about the tool. I
hope it is helpful to you.

Also, how did you hear about WormClust?

Thanks
Shivani

**Comment by n-szulc** [comment]
Hi Shivani

thank you for your reply, we will definitely try the tool in our lab. 

I learned about WormClust from your preprint, which I came across on Twitter.

Best,
Natalia

**Comment by shivani710** [comment]
Thanks Natalia. Glad to know that you will be trying it out. Hope it is
helpful to you. Looking forward to any feedback from you in the future.

Best
Shivani
